name: Newman API Tests
on: [push, pull_request]

jobs: 
  test: 
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v2
      - 
        uses: actions/setup-node@v2
        with: 
          node-version: "18"
      - 
        name: "Install newman"
        run: "npm install -g newman"
      - 
        name: "Install newman reporter"
        run: "npm install -g newman-reporter-htmlextra"
      - 
        name: "Run tests"
        run: newman run "Restful Booker BVT.postman_collection.json" -e Production.postman_environment.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html
      
      - name: Publish report
        uses: MeilCli/slack-upload-file@v1
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          file_path: './tests/htmlreport.html'
          file_name: 'postmanReport.html'
          file_type: 'html'
          channels: 'api-test-reports'